# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: gobank
    ports:
      - 5432:5432
    volumes:
      - ./tmpdatabase:/var/lib/postgresql/data
